name: test inputs
inputs:
  org:
    type: string
secrets:
  testsecret:
    
runs:
  using: "composite"
  steps:
    - run: echo  ${{inputs.org}}
      shell: bash
    - run: |
        image_tag='bob'
        echo  "IMAGE_TAG=$image_tag" >> $GITHUB_ENV
      shell: bash
    - run: echo  ${IMAGE_TAG}
      shell: bash
      
