name: test inputs
inputs:
  org:
    type: string
outputs:
  specific_version:
    value: ${{ steps.get_something.outputs.specific_version }}
    
runs:
  using: "composite"
  steps:
    - id: get_something
      shell: bash
      run: |
        somedata="this is a thing"
        echo "::set-output name=specific_version::$somedata"
    - run: echo  ${{inputs.org}}
      shell: bash
    - run: |
        image_tag='bob'
        echo  "IMAGE_TAG=$image_tag" >> $GITHUB_ENV
      shell: bash
    - run: echo  ${IMAGE_TAG}
      shell: bash
      
    - run: echo  "SPECIFC=${{ steps.get_something.outputs.specific_version }}" >> $GITHUB_ENV
      shell: bash
    - run: echo  ${SPECIFC}
      shell: bash
      
