name: test inputs
inputs:
  org:
    type: string
    
runs:
  using: "composite"
  steps:
    - run: echo  ${{ github.event.inputs.org }}
      shell: bash

    - run: echo  ${{inputs.org}}
      shell: bash
