name: test inputs
inputs:
  org:
    type: string
    
runs:
  using: "composite"
  steps:
    - run: echo  ${{ INPUT_ORG }}
      shell: bash
    - run: echo  ${{ github.event.inputs.org }}
      shell: bash
