name: test inputs
inputs:
  org:
    type: string
    default: "${{env.ORGNAME}}"
secrets:
  testsecret:
    
runs:
  using: "composite"
  steps:
    - run: echo  ${{inputs.org}}
      shell: bash
      
