# Build this package and create the docker containers etc
name: Build

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      org:
        required: true
        type: string
      coordinator:
        required: true
        type: string
    secrets:
      token:
        required: true


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.repository.name }}" 
      - run: echo "${{ github.event.repository_owner }}" 
      - run: echo "${{ github.repository.name }}" 
      - run: echo "${{ github.repository_owner }}" 
      - run: echo "${{ inputs.org }}" 
