# Build this package and create the docker containers etc
name: Build

on:
  workflow_call:
    inputs:
      org:
        required: true
        type: string
        description: "the name of the private org to ensure we don't run on forks"
      coordinator:
        required: true
        type: string
        description: "the name of the repo that has helper actions in it"
    secrets:
      token:
        required: true
        description: "org specific token"
      ci_username:
        required: true
        description: "CI username"
      ci_user_email:
        required: true
        description: "CI user email"
      ci_github_token:
        required: true
        description: "CI github token"
      ci_access_token:
        required: true
        description: "CI access token"
      docker_registry:
        required: true
        description: "docker registry"
      docker_username:
        required: true
        description: "docker username"
      docker_password:
        required: true
        description: "docker password"
      


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.repository.name }}" 
      - run: echo "${{ github.event.repository_owner }}" 
      - run: echo "${{ github.repository.name }}" 
      - run: echo "${{ github.repository_owner }}" 
      - run: echo "${{ inputs.org }}" 
