name: quick test
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test-inputs
        with:
          org: bob
