name: quick test
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ORGNAME=env_iorg" >> GITHUB_ENV
        shell: bash
      - run: echo $ORGNAME
        shell: bash
      - uses: actions/checkout@v2
      - uses: kvasira/i_github_utils/.github/actions/create_image_tag@main
        with:
          package_version: 0.1.1

